//
// ChannelAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import RealmSwift

open class ChannelAPI{
    /**
     频道列表
     
     - parameter s: (query) 否(默认 1) 上线状态，0 或 1 (optional, default to 1)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func nsChsGet(s: String? = nil, completion: (() -> Void)? = nil) {
        
        let path = "/ns/chs"
        let URLString = SimpleRequest.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [
            "s": s as Optional<AnyObject>
        ]
        
        
        let parameters = APIHelper.rejectNil(nillableParameters)
        let convertedParameters = APIHelper.convertBoolToString(parameters)
        
        SimpleRequest.budileRequest(URLString, method: .get, parameters: convertedParameters, encoding: URLEncoding.default, headers: nil).request { (data, error, _) in
            self.AnalysisChannelObject(data as AnyObject?)
            
            completion?()
        }
    }
}



private extension ChannelAPI{
    
    /**
     处理频道获取的数据 
     - 处理 respones 数据中的 data 集合
     － 完善数据库的数据注入
     － 以及后续数据的基本处理，
     － 科技 外媒 点集 的排序
     － 美文 趣图 等频道的默认 不展示处理
     －以及对于 #美女# 频道的躲避审核期的删除
     */
    class func AnalysisChannelObject(_ data:AnyObject?){
        
        let realm = try! Realm()
        
        if let code = data?.object(forKey: "code") as? Int , code == 2000,let datas = data?.object(forKey: "data") as? NSArray{
            
            let incount = realm.objects(Channel.self).count <= 0 // 如果数据库中没有任何数据 那么需要做一些初始化的操作
            
            try! realm.write({
                for channel in datas {
                    realm.create(Channel.self, value: channel, update: true)
                }
            })
            
            try! realm.write({
                realm.objects(Channel.self).filter("cname = '奇点'").setValue(0, forKey: "orderindex")
                
                if incount {
                    realm.objects(Channel.self).filter("cname = '科技'").setValue(1, forKey: "orderindex")
                    realm.objects(Channel.self).filter("cname = '外媒'").setValue(2, forKey: "orderindex")
                    realm.objects(Channel.self).filter("cname = '点集'").setValue(3, forKey: "orderindex")
                    
                    realm.objects(Channel.self).filter("cname = '美文'").setValue(1, forKey: "isdelete")
                    realm.objects(Channel.self).filter("cname = '趣图'").setValue(1, forKey: "isdelete")
                    realm.objects(Channel.self).filter("cname = '奇闻'").setValue(1, forKey: "isdelete")
                    realm.objects(Channel.self).filter("cname = '萌宠'").setValue(1, forKey: "isdelete")
                    realm.objects(Channel.self).filter("cname = '自媒体'").setValue(1, forKey: "isdelete")
                    realm.objects(Channel.self).filter("cname = '科学'").setValue(1, forKey: "isdelete")
                    realm.objects(Channel.self).filter("cname = '养生'").setValue(1, forKey: "isdelete")
                    realm.objects(Channel.self).filter("cname = '股票'").setValue(1, forKey: "isdelete")
                }
                
//                if let del = realm.objects(Channel).filter("cname = '美女'").first {
//                    
//                    realm.delete(del)
//                }
            })
        }
    }
}
