//// Models.swift
////
//// Generated by swagger-codegen
//// https://github.com/swagger-api/swagger-codegen
////
//
import Foundation

protocol JSONEncodable {
    func encodeToJSON() -> AnyObject
}
